apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
  namespace: seaweedfs
type: Opaque
stringData:
  # S3 credentials configuration for SeaweedFS
  # Format: JSON with identities
  config.json: |
    {
      "identities": [
        {
          "name": "mimir",
          "credentials": [
            {
              "accessKey": "mimir-access-key",
              "secretKey": "mimir-secret-key-change-me"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write",
            "List",
            "Tagging"
          ]
        }
      ]
    }
