# Storage Classes for Mimir Monitoring Stack
# Two classes: one for Mimir+SeaweedFS, one for Monitoring

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mimir
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: monitoring
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
