# ArgoCD Application for Grafana Mimir
# Deploy to mimir namespace using local chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    # Local chart from this repo (v5.8.0 pinned, avoids Kafka dependency in v6.x)
    repoURL: https://github.com/YOUR_ORG/mimir-work.git  # TODO: Update with your repo URL
    targetRevision: HEAD
    path: mimir-distributed
    helm:
      valueFiles:
        - ../mimir-values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
